# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hack', '0002_auto_20160710_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='hack',
            name='slug',
            field=models.SlugField(default='aa', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=models.SlugField(default='aa', max_length=155),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
