# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_confirmed', models.BooleanField(default=False)),
                ('activation_key', models.CharField(blank=True, max_length=40, verbose_name='activation key')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userextra', to='accounts.User', verbose_name='user')),
            ],
        ),
    ]
